### ISSUE TITLE
rigidity maps ?

### ISSUE THREAD

**Issue by lulu1315** [jswulff/mrflow#3]
hello and thanks for the code!
are you planning to publish your code to generate the rigidity maps ?
or are there existing projects to do that already available .. ?
thanks in advance
luc

**Comment by jswulff** [comment]
Hi Luc,

The CNNs to generate the rigidity maps is now online at http://files.is.tue.mpg.de/jwulff/mrflow/semantic_rigiditsemantic_rigidity_cvpr2017.zip .

However, you can also use any other semantic segmentation code, manually define some objects classes as rigid and others as nonrigid, and feed the resulting binary masks to the MR-Flow code.

Hope this helps!

**Comment by Tetsujinfr** [comment]
what is the syntax if I want to use your rigidity cnn trained model? Can I just extract all the content of the zip under the subfolder "rigidity" and then simply use the rigidity flag of mrflow.py ?
thanks
Tets

**Comment by jswulff** [comment]
Hi Tets,

The semantic CNN is a separate piece of code that generates the rigidity maps as PNG files. You can then pass these PNG files as parameters to mrflow.py.

For details about how to use the trained CNN to generate rigidity maps, please see the README file in the archive containing the trained models.
